// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicInfoPanel,
  DefaultInfoPanelProps
} from "./plasmic/d_d_npc_generator/PlasmicInfoPanel";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import {ALIGNMENT, NPC} from "../models/npc";

export interface InfoPanelProps extends DefaultInfoPanelProps {
  npc?: NPC;
}

function heightConversion(heightInInches: number): string {
  const inches = heightInInches % 12;
  const feet = (heightInInches - inches) / 12;
  return `${feet} ft ${inches} in`;
}

function InfoPanel_(props: InfoPanelProps, ref: HTMLElementRefOf<"div">) {
  const rest = props as DefaultInfoPanelProps;
  const npc = props.npc;

  if (!npc) {
    return <div></div>
  }

  return <PlasmicInfoPanel
    root={{ ref }}
    name2={{ props: { children: `${npc.first_name} ${npc.last_name}`} }}
    name={{ props: { children: npc.race } }}
    age={{ props: { children: npc.age } }}
    gender={{ props: { children: npc.gender ? 'Male' : 'Female' } }}
    height={{ props: { children: heightConversion(npc.height_inches) } }}
    height2={{ props: { children: `${npc.weight_lbs} lbs` } }}
    descriptionBox={{ props: { children: <p style={{color: 'black'}}>{npc.physical_description}</p>, style: {overflowY: 'scroll'} } }}
    str={{ props: { children: npc.str } }}
    dex={{ props: { children: npc.dex } }}
    con={{ props: { children: npc.con } }}
    int={{ props: { children: npc.int } }}
    wis={{ props: { children: npc.wis } }}
    cha={{ props: { children: npc.cha } }}
    alignment={{ props: { children: ALIGNMENT[npc.alignment] } }}
    job={{ props: { children: npc.class } }}
    personalityBox={{ props: { children: <p style={{color: 'black'}}>{npc.personality_description}</p>, style: {overflowY: 'scroll'} } }}
    historyBox={{ props: { children: <p style={{color: 'black'}}>{npc.history}</p>, style: {overflowY: 'scroll'} } }}
    plotBox={{ props: { children: <p style={{color: 'black'}}>{npc.plot_hook}</p>, style: {overflowY: 'scroll'} } }}
    portrait={{
      props: npc.portrait != null?{src: npc.portrait}:{}
    }}
    {...rest}
  />;
}

const InfoPanel = React.forwardRef(InfoPanel_);
export default InfoPanel;
