// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: b5WcywRoms9zdBws8HK6N7
// Component: Aj6PI_7LPB7
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Select from "../../Select"; // plasmic-import: _p3h-q-1811/component
import Select__Option from "../../Select__Option"; // plasmic-import: AQwZIy0fAMn/component
import Checkbox from "../../Checkbox"; // plasmic-import: nPjHAnzGVYU/component
import { Slider } from "@plasmicpkgs/antd/skinny/registerSlider"; // plasmic-import: iBC45mjTXv/codeComponent
import TextInput from "../../TextInput"; // plasmic-import: fvt7-zOYU04/component
import Button from "../../Button"; // plasmic-import: xeFM0tPhg2-/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_d_d_npc_generator.module.css"; // plasmic-import: b5WcywRoms9zdBws8HK6N7/projectcss
import sty from "./PlasmicGenerateSelector.module.css"; // plasmic-import: Aj6PI_7LPB7/css

import InfoIcon from "./icons/PlasmicIcon__Info"; // plasmic-import: f0bJZJ00T/icon
import SearchsvgIcon from "./icons/PlasmicIcon__Searchsvg"; // plasmic-import: _92sYGu6Vhw/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: 8d9W5hPSEbQ/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: pnFO32SGCAi/icon

export type PlasmicGenerateSelector__VariantMembers = {
  tavern: "tavern";
};
export type PlasmicGenerateSelector__VariantsArgs = {
  tavern?: SingleBooleanChoiceArg<"tavern">;
};
type VariantPropType = keyof PlasmicGenerateSelector__VariantsArgs;
export const PlasmicGenerateSelector__VariantProps = new Array<VariantPropType>(
  "tavern"
);

export type PlasmicGenerateSelector__ArgsType = {};
type ArgPropType = keyof PlasmicGenerateSelector__ArgsType;
export const PlasmicGenerateSelector__ArgProps = new Array<ArgPropType>();

export type PlasmicGenerateSelector__OverridesType = {
  root?: p.Flex<"div">;
  genderSelect?: p.Flex<typeof Select>;
  raceSelect?: p.Flex<typeof Select>;
  alignmentSelect?: p.Flex<typeof Select>;
  abilityScoreSelect?: p.Flex<typeof Select>;
  jobSelect?: p.Flex<typeof Select>;
  plotHookCheck?: p.Flex<typeof Checkbox>;
  genderSlider?: p.Flex<typeof Slider>;
  primaryRaceSelect?: p.Flex<typeof Select>;
  diversitySelect?: p.Flex<typeof Select>;
  economicsSelect?: p.Flex<typeof Select>;
  economicsSelect2?: p.Flex<typeof Select>;
  plotHookPercentage?: p.Flex<typeof TextInput>;
  totalCount?: p.Flex<typeof TextInput>;
  generate?: p.Flex<typeof Button>;
  swapView?: p.Flex<"div">;
};

export interface DefaultGenerateSelectorProps {
  tavern?: SingleBooleanChoiceArg<"tavern">;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicGenerateSelector__RenderFunc(props: {
  variants: PlasmicGenerateSelector__VariantsArgs;
  args: PlasmicGenerateSelector__ArgsType;
  overrides: PlasmicGenerateSelector__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const stateSpecs = React.useMemo(
    () => [
      {
        path: "tavern",
        type: "private",
        variableType: "variant",
        initFunc: true ? ($props, $state, $ctx) => $props.tavern : undefined
      }
    ],
    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, $props, $ctx);

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root,
        { [sty.roottavern]: hasVariant($state, "tavern", "tavern") }
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__vygwa,
          {
            [sty.texttavern__vygwa6EOuz]: hasVariant($state, "tavern", "tavern")
          }
        )}
      >
        {hasVariant($state, "tavern", "tavern")
          ? "Fill My Tavern!"
          : "Generate an NPC"}
      </div>

      {(hasVariant($state, "tavern", "tavern") ? true : true) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox___2276G, {
            [sty.freeBoxtavern___2276G6EOuz]: hasVariant(
              $state,
              "tavern",
              "tavern"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__i7Z0P
            )}
          >
            {"Gender"}
          </div>

          <Select
            data-plasmic-name={"genderSelect"}
            data-plasmic-override={overrides.genderSelect}
            className={classNames("__wab_instance", sty.genderSelect)}
            color={"clear" as const}
            placeholder={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3NIn0
                )}
              >
                {"Select…"}
              </div>
            }
            selectedContent={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zDlfW
                )}
              >
                {"Selected"}
              </div>
            }
          />
        </p.Stack>
      ) : null}
      {(hasVariant($state, "tavern", "tavern") ? true : true) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__fWqOw, {
            [sty.freeBoxtavern__fWqOw6EOuz]: hasVariant(
              $state,
              "tavern",
              "tavern"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___6SOMk
            )}
          >
            {"Race"}
          </div>

          <Select
            data-plasmic-name={"raceSelect"}
            data-plasmic-override={overrides.raceSelect}
            className={classNames("__wab_instance", sty.raceSelect)}
            color={"clear" as const}
            placeholder={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qhhCc
                )}
              >
                {"Select…"}
              </div>
            }
            selectedContent={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rrDrL
                )}
              >
                {"Selected"}
              </div>
            }
          />
        </p.Stack>
      ) : null}
      {(hasVariant($state, "tavern", "tavern") ? true : true) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__xvhQ5, {
            [sty.freeBoxtavern__xvhQ56EOuz]: hasVariant(
              $state,
              "tavern",
              "tavern"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__mmHRd
            )}
          >
            {"Alignment"}
          </div>

          <Select
            data-plasmic-name={"alignmentSelect"}
            data-plasmic-override={overrides.alignmentSelect}
            className={classNames("__wab_instance", sty.alignmentSelect)}
            color={"clear" as const}
            placeholder={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mfdsW
                )}
              >
                {"Select…"}
              </div>
            }
            selectedContent={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__owfoi
                )}
              >
                {"Selected"}
              </div>
            }
          />
        </p.Stack>
      ) : null}
      {(hasVariant($state, "tavern", "tavern") ? true : true) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__dJmmO, {
            [sty.freeBoxtavern__dJmmO6EOuz]: hasVariant(
              $state,
              "tavern",
              "tavern"
            )
          })}
        >
          <div className={classNames(projectcss.all, sty.freeBox__fPnxN)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__iLiRs
              )}
            >
              {"Ability Scores"}
            </div>

            <InfoIcon
              className={classNames(projectcss.all, sty.svg__wXq3R)}
              role={"img"}
            />
          </div>

          <Select
            data-plasmic-name={"abilityScoreSelect"}
            data-plasmic-override={overrides.abilityScoreSelect}
            className={classNames("__wab_instance", sty.abilityScoreSelect)}
            color={"clear" as const}
            placeholder={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8H9Lu
                )}
              >
                {"Select…"}
              </div>
            }
            selectedContent={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__phpLi
                )}
              >
                {"Selected"}
              </div>
            }
          />
        </p.Stack>
      ) : null}
      {(hasVariant($state, "tavern", "tavern") ? true : true) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__mboWq, {
            [sty.freeBoxtavern__mboWq6EOuz]: hasVariant(
              $state,
              "tavern",
              "tavern"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___8IuZg
            )}
          >
            {"Class/Profession"}
          </div>

          <Select
            data-plasmic-name={"jobSelect"}
            data-plasmic-override={overrides.jobSelect}
            className={classNames("__wab_instance", sty.jobSelect)}
            color={"clear" as const}
            placeholder={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cVlnv
                )}
              >
                {"Select…"}
              </div>
            }
            selectedContent={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__p2Ny9
                )}
              >
                {"Selected"}
              </div>
            }
          />
        </p.Stack>
      ) : null}
      {(hasVariant($state, "tavern", "tavern") ? true : true) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox___5FMj4, {
            [sty.freeBoxtavern___5FMj46EOuz]: hasVariant(
              $state,
              "tavern",
              "tavern"
            )
          })}
        >
          <div className={classNames(projectcss.all, sty.freeBox__vxGCr)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___2Lr6Y
              )}
            >
              {"Plot Hook"}
            </div>

            <Checkbox
              data-plasmic-name={"plotHookCheck"}
              data-plasmic-override={overrides.plotHookCheck}
              className={classNames("__wab_instance", sty.plotHookCheck)}
            />
          </div>
        </p.Stack>
      ) : null}
      {(hasVariant($state, "tavern", "tavern") ? true : false) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox___16H3S, {
            [sty.freeBoxtavern___16H3S6EOuz]: hasVariant(
              $state,
              "tavern",
              "tavern"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__ui
            )}
          >
            {"Gender Distribution"}
          </div>

          <div
            className={classNames(projectcss.all, sty.freeBox__yw0Vt, {
              [sty.freeBoxtavern__yw0Vt6EOuz]: hasVariant(
                $state,
                "tavern",
                "tavern"
              )
            })}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kgMvU,
                {
                  [sty.texttavern__kgMvU6EOuz]: hasVariant(
                    $state,
                    "tavern",
                    "tavern"
                  )
                }
              )}
            >
              {"Male"}
            </div>

            <Slider
              data-plasmic-name={"genderSlider"}
              data-plasmic-override={overrides.genderSlider}
              className={classNames("__wab_instance", sty.genderSlider, {
                [sty.genderSlidertavern]: hasVariant($state, "tavern", "tavern")
              })}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__yzplE,
                {
                  [sty.texttavern__yzplE6EOuz]: hasVariant(
                    $state,
                    "tavern",
                    "tavern"
                  )
                }
              )}
            >
              {"Female"}
            </div>
          </div>
        </p.Stack>
      ) : null}
      {(hasVariant($state, "tavern", "tavern") ? true : true) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__qky8D, {
            [sty.freeBoxtavern__qky8D6EOuz]: hasVariant(
              $state,
              "tavern",
              "tavern"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__f7PHn,
              {
                [sty.texttavern__f7PHn6EOuz]: hasVariant(
                  $state,
                  "tavern",
                  "tavern"
                )
              }
            )}
          >
            {hasVariant($state, "tavern", "tavern") ? "Primary Race" : "Gender"}
          </div>

          <Select
            data-plasmic-name={"primaryRaceSelect"}
            data-plasmic-override={overrides.primaryRaceSelect}
            className={classNames("__wab_instance", sty.primaryRaceSelect, {
              [sty.primaryRaceSelecttavern]: hasVariant(
                $state,
                "tavern",
                "tavern"
              )
            })}
            color={"clear" as const}
            placeholder={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dylCt
                )}
              >
                {"Select…"}
              </div>
            }
            selectedContent={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__szSqE
                )}
              >
                {"Selected"}
              </div>
            }
          />
        </p.Stack>
      ) : null}
      {(hasVariant($state, "tavern", "tavern") ? true : false) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__u4Th7, {
            [sty.freeBoxtavern__u4Th76EOuz]: hasVariant(
              $state,
              "tavern",
              "tavern"
            )
          })}
        >
          <div className={classNames(projectcss.all, sty.freeBox__zVfdf)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__c6Ry
              )}
            >
              {"Diversity"}
            </div>

            <InfoIcon
              className={classNames(projectcss.all, sty.svg__oMqFh)}
              role={"img"}
            />
          </div>

          <Select
            data-plasmic-name={"diversitySelect"}
            data-plasmic-override={overrides.diversitySelect}
            className={classNames("__wab_instance", sty.diversitySelect)}
            color={"clear" as const}
            placeholder={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ywtro
                )}
              >
                {"Select…"}
              </div>
            }
            selectedContent={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eGlAt
                )}
              >
                {"Selected"}
              </div>
            }
          />
        </p.Stack>
      ) : null}
      {(hasVariant($state, "tavern", "tavern") ? true : false) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox___7GqXv, {
            [sty.freeBoxtavern___7GqXv6EOuz]: hasVariant(
              $state,
              "tavern",
              "tavern"
            )
          })}
        >
          <div className={classNames(projectcss.all, sty.freeBox___7RXyD)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___65OS
              )}
            >
              {"Economic Distribution"}
            </div>

            <InfoIcon
              className={classNames(projectcss.all, sty.svg__xiAx9)}
              role={"img"}
            />
          </div>

          <Select
            data-plasmic-name={"economicsSelect"}
            data-plasmic-override={overrides.economicsSelect}
            className={classNames("__wab_instance", sty.economicsSelect)}
            color={"clear" as const}
            placeholder={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sXe7
                )}
              >
                {"Select…"}
              </div>
            }
            selectedContent={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dyIvu
                )}
              >
                {"Selected"}
              </div>
            }
          />
        </p.Stack>
      ) : null}
      {(hasVariant($state, "tavern", "tavern") ? true : false) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__czdD, {
            [sty.freeBoxtavern__czdD6EOuz]: hasVariant(
              $state,
              "tavern",
              "tavern"
            )
          })}
        >
          <div className={classNames(projectcss.all, sty.freeBox__q9MQy)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qdTm9
              )}
            >
              {"Alignment Distribution"}
            </div>

            <InfoIcon
              className={classNames(projectcss.all, sty.svg__l1Bt)}
              role={"img"}
            />
          </div>

          <Select
            data-plasmic-name={"economicsSelect2"}
            data-plasmic-override={overrides.economicsSelect2}
            className={classNames("__wab_instance", sty.economicsSelect2)}
            color={"clear" as const}
            placeholder={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vFy3U
                )}
              >
                {"Select…"}
              </div>
            }
            selectedContent={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__n2Eb0
                )}
              >
                {"Selected"}
              </div>
            }
          />
        </p.Stack>
      ) : null}
      {(hasVariant($state, "tavern", "tavern") ? true : false) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox___8QlD, {
            [sty.freeBoxtavern___8QlD6EOuz]: hasVariant(
              $state,
              "tavern",
              "tavern"
            )
          })}
        >
          <div className={classNames(projectcss.all, sty.freeBox___3Bebs)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__uXY
              )}
            >
              {"Plot Hooks"}
            </div>

            <TextInput
              data-plasmic-name={"plotHookPercentage"}
              data-plasmic-override={overrides.plotHookPercentage}
              className={classNames("__wab_instance", sty.plotHookPercentage, {
                [sty.plotHookPercentagetavern]: hasVariant(
                  $state,
                  "tavern",
                  "tavern"
                )
              })}
              placeholder={"0" as const}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__s0Xnj,
                {
                  [sty.texttavern__s0Xnj6EOuz]: hasVariant(
                    $state,
                    "tavern",
                    "tavern"
                  )
                }
              )}
            >
              {"%"}
            </div>
          </div>
        </p.Stack>
      ) : null}
      {(hasVariant($state, "tavern", "tavern") ? true : false) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox___6LMol, {
            [sty.freeBoxtavern___6LMol6EOuz]: hasVariant(
              $state,
              "tavern",
              "tavern"
            )
          })}
        >
          <div className={classNames(projectcss.all, sty.freeBox___4GHuP)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__sccWg
              )}
            >
              {"Number (Max 100)"}
            </div>

            <TextInput
              data-plasmic-name={"totalCount"}
              data-plasmic-override={overrides.totalCount}
              className={classNames("__wab_instance", sty.totalCount, {
                [sty.totalCounttavern]: hasVariant($state, "tavern", "tavern")
              })}
              placeholder={"0" as const}
            />
          </div>
        </p.Stack>
      ) : null}

      <Button
        data-plasmic-name={"generate"}
        data-plasmic-override={overrides.generate}
        className={classNames("__wab_instance", sty.generate)}
        color={"sand" as const}
        shape={"round" as const}
      >
        {"Generate!"}
      </Button>

      <div
        data-plasmic-name={"swapView"}
        data-plasmic-override={overrides.swapView}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.swapView,
          { [sty.swapViewtavern]: hasVariant($state, "tavern", "tavern") }
        )}
      >
        {hasVariant($state, "tavern", "tavern")
          ? "I just need one person!"
          : "I want a whole tavern!"}
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "genderSelect",
    "raceSelect",
    "alignmentSelect",
    "abilityScoreSelect",
    "jobSelect",
    "plotHookCheck",
    "genderSlider",
    "primaryRaceSelect",
    "diversitySelect",
    "economicsSelect",
    "economicsSelect2",
    "plotHookPercentage",
    "totalCount",
    "generate",
    "swapView"
  ],
  genderSelect: ["genderSelect"],
  raceSelect: ["raceSelect"],
  alignmentSelect: ["alignmentSelect"],
  abilityScoreSelect: ["abilityScoreSelect"],
  jobSelect: ["jobSelect"],
  plotHookCheck: ["plotHookCheck"],
  genderSlider: ["genderSlider"],
  primaryRaceSelect: ["primaryRaceSelect"],
  diversitySelect: ["diversitySelect"],
  economicsSelect: ["economicsSelect"],
  economicsSelect2: ["economicsSelect2"],
  plotHookPercentage: ["plotHookPercentage"],
  totalCount: ["totalCount"],
  generate: ["generate"],
  swapView: ["swapView"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  genderSelect: typeof Select;
  raceSelect: typeof Select;
  alignmentSelect: typeof Select;
  abilityScoreSelect: typeof Select;
  jobSelect: typeof Select;
  plotHookCheck: typeof Checkbox;
  genderSlider: typeof Slider;
  primaryRaceSelect: typeof Select;
  diversitySelect: typeof Select;
  economicsSelect: typeof Select;
  economicsSelect2: typeof Select;
  plotHookPercentage: typeof TextInput;
  totalCount: typeof TextInput;
  generate: typeof Button;
  swapView: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicGenerateSelector__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicGenerateSelector__VariantsArgs;
    args?: PlasmicGenerateSelector__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicGenerateSelector__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicGenerateSelector__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicGenerateSelector__ArgProps,
          internalVariantPropNames: PlasmicGenerateSelector__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicGenerateSelector__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGenerateSelector";
  } else {
    func.displayName = `PlasmicGenerateSelector.${nodeName}`;
  }
  return func;
}

export const PlasmicGenerateSelector = Object.assign(
  // Top-level PlasmicGenerateSelector renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    genderSelect: makeNodeComponent("genderSelect"),
    raceSelect: makeNodeComponent("raceSelect"),
    alignmentSelect: makeNodeComponent("alignmentSelect"),
    abilityScoreSelect: makeNodeComponent("abilityScoreSelect"),
    jobSelect: makeNodeComponent("jobSelect"),
    plotHookCheck: makeNodeComponent("plotHookCheck"),
    genderSlider: makeNodeComponent("genderSlider"),
    primaryRaceSelect: makeNodeComponent("primaryRaceSelect"),
    diversitySelect: makeNodeComponent("diversitySelect"),
    economicsSelect: makeNodeComponent("economicsSelect"),
    economicsSelect2: makeNodeComponent("economicsSelect2"),
    plotHookPercentage: makeNodeComponent("plotHookPercentage"),
    totalCount: makeNodeComponent("totalCount"),
    generate: makeNodeComponent("generate"),
    swapView: makeNodeComponent("swapView"),

    // Metadata about props expected for PlasmicGenerateSelector
    internalVariantProps: PlasmicGenerateSelector__VariantProps,
    internalArgProps: PlasmicGenerateSelector__ArgProps
  }
);

export default PlasmicGenerateSelector;
/* prettier-ignore-end */
